### ISSUE TITLE
Bug - Enable JWT Parser to Work for Windows and Unix-Base Systems When Ran in Docker

### ISSUE THREAD

**Issue by jorg3lopez** [CDCgov/trusted-intermediary#1244]
# Bug

JwtEngine throws a parser error when parsing our public key.

## Describe the Bug

When running TI in docker on a Windows environment, the jwt parser fails as it detects `\r\n` end of line characters.

## Impact

Unable to run API correctly as the auth endpoint throws exceptions.

## To Reproduce

1. Be on a Windows environment
2. run TI using docker
3. request an access token by hitting the auth endpoint

## Expected Behavior

Be able to acquire an access token when hitting the auth endpoint.

## Screenshots

<img width="1142" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlpiQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fee9c70e0df4e63428c2e7e89748d7f359ab7494/image.png" alt="image.png" />

<img width="1588" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGxiQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dab624cdb089c617cfe10b0761603d1846d4b9cc/image.png" alt="image.png" />

## Logs

```
 2024-08-14 20:17:19,067 [main] INFO  - Using Hikari default DB Max Lifetime
router-1  | {"@timestamp":"2024-08-14T20:17:19.182659116Z","level":"INFO","message":"Reflections took 107 ms to scan 1 urls, producing 38 keys and 191 values","thread_name":"main"}
router-1  | 2024-08-14 20:17:19,200 [main] INFO  - Registering:
router-1  | 2024-08-14 20:17:19,209 [main] INFO  - verb: GET, endpoint: /v1/etor/metadata/summary/{sender}
router-1  | 2024-08-14 20:17:19,209 [main] INFO  - verb: GET, endpoint: /v1/etor/metadata/{id}
router-1  | 2024-08-14 20:17:19,209 [main] INFO  - verb: POST, endpoint: /v1/etor/orders
router-1  | 2024-08-14 20:17:19,209 [main] INFO  - verb: POST, endpoint: /v1/etor/results
router-1  | 2024-08-14 20:17:19,210 [main] INFO  - verb: POST, endpoint: /v1/auth/token
router-1  | 2024-08-14 20:17:56,419 [JettyServerThreadPool-31] INFO  - POST http://localhost:8080/v1/auth/token
router-1  | 2024-08-14 20:17:56,425 [JettyServerThreadPool-31] INFO  - Parsing login request via JWT
router-1  | 2024-08-14 20:17:56,431 [JettyServerThreadPool-31] INFO  - Validating that organization report-stream exists
router-1  | 2024-08-14 20:17:56,431 [JettyServerThreadPool-31] INFO  - Organization report-stream exists, validating their token
router-1  | 2024-08-14 20:17:56,432 [JettyServerThreadPool-31] INFO  - Acquiring local key organization-report-stream-public-key-local
router-1  | 2024-08-14 20:17:56,432 [JettyServerThreadPool-31] INFO  - Successfully got local key organization-report-stream-public-key-local
router-1  | 2024-08-14 20:17:56,434 [JettyServerThreadPool-31] ERROR - Authentication failed
router-1  | gov.hhs.cdc.trustedintermediary.wrappers.InvalidTokenException: java.lang.IllegalArgumentException: Illegal base64 character d
router-1  |     at gov.hhs.cdc.trustedintermediary.external.jjwt.JjwtEngine.validateToken(JjwtEngine.java:120)
router-1  |     at gov.hhs.cdc.trustedintermediary.auth.RequestSessionTokenUsecase.getToken(RequestSessionTokenUsecase.java:57)
router-1  |     at gov.hhs.cdc.trustedintermediary.auth.AuthDomainRegistration.handleAuth(AuthDomainRegistration.java:59)
router-1  |     at gov.hhs.cdc.trustedintermediary.external.javalin.DomainsRegistration.processRequest(DomainsRegistration.java:148)
router-1  |     at gov.hhs.cdc.trustedintermediary.external.javalin.DomainsRegistration.lambda$createHandler$4(DomainsRegistration.java:128)
router-1  |     at io.javalin.router.Endpoint.handle(Endpoint.kt:52)
router-1  |     at io.javalin.router.ParsedEndpoint.handle(ParsedEndpoint.kt:15)
router-1  |     at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$9$lambda$7$lambda$6(DefaultTasks.kt:52)
router-1  |     at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:99)
router-1  |     at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:64)
router-1  |     at io.javalin.http.servlet.JavalinServlet.handle(JavalinServlet.kt:50)
router-1  |     at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:30)
router-1  |     at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
router-1  |     at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:52)
router-1  |     at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
router-1  |     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
router-1  |     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
router-1  |     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
router-1  |     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
router-1  |     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
router-1  |     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
router-1  |     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
router-1  |     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
router-1  |     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
router-1  |     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
router-1  |     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
router-1  |     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
router-1  |     at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
router-1  |     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
router-1  |     at org.eclipse.jetty.server.Server.handle(Server.java:563)
router-1  |     at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
router-1  |     at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
router-1  |     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
router-1  |     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
router-1  |     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
router-1  |     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
router-1  |     at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
router-1  |     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
router-1  |     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
router-1  |     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
router-1  |     at java.base/java.lang.Thread.run(Thread.java:840)
router-1  | Caused by: java.lang.IllegalArgumentException: Illegal base64 character d
router-1  |     at java.base/java.util.Base64$Decoder.decode0(Base64.java:848)
router-1  |     at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
router-1  |     at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
router-1  |     at gov.hhs.cdc.trustedintermediary.external.jjwt.JjwtEngine.parseBase64(JjwtEngine.java:148)
router-1  |     at gov.hhs.cdc.trustedintermediary.external.jjwt.JjwtEngine.readPublicKey(JjwtEngine.java:141)
router-1  |     at gov.hhs.cdc.trustedintermediary.external.jjwt.JjwtEngine.validateToken(JjwtEngine.java:116)
router-1  |     ... 40 common frames omitted
router-1  | 2024-08-14 20:17:56,438 [JettyServerThreadPool-31] INFO  - Constructing the response
router-1  | 2024-08-14 20:17:56,440 [JettyServerThreadPool-31] INFO  - Handler complete
```

## Additional Context
We have a [PR ](https://github.com/CDCgov/trusted-intermediary/pull/1241)with the fix.

**Comment by jorg3lopez** [comment]
Bug fix [PR ](https://github.com/CDCgov/trusted-intermediary/pull/1241)has been merged to the code base.
