### ISSUE TITLE
Bug: Outbound Orders Stuck in Not Delivering State

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#815]
# Backlog Task

ReportStream fails to deliver messages forwarded from the TI service.

Example submission ID: 3672530 (from simulated hospital to RS) & 3672538 (from TI to RS)

Sample message:
https://github.com/CDCgov/trusted-intermediary/blob/main/examples/MN/003_MN_ORM_O01_NBS.hl7
... minus the first of the two OBRs:
 `MSH|^~\&|Epic^1.2.840.114350.1.13.145.2.7.2.695071^ISO|Centracare^centracare.com^DNS|NATUS^natus.health.state.mn.us^DNS|MN Public Health Lab^2.16.840.1.114222.4.1.10080^ISO|20230506052916-0500||ORM^O01^ORM_O01|31808297|P|2.5.1|||AL|AL|||||LAB_PRU_COMPONENT^^2.16.840.1.113883.9.82^ISO~LAB_TO_COMPONENT^^2.16.840.1.113883.9.22^ISO
PID|1||11102779^^^CRPMRN^MR||SMITH^BB SARAH^^^^^L|SMITH^SADIE^S|20230504131023-0500|M|||555 STATE HIGHWAY 13^^DEER CREEK^MN^56527-9657^USA^H^^OTTER TAIL||^^PH^^^763^5555555^^(763)555-5555|||||||||||N|1|||||N
ORC|NW|421832901^EPIC^1.2.840.114350.1.13.145.2.7.2.695071^ISO|||||||20230506052913-0500|||1265136360^JONES^JANE^^^^^^NPI^L^^^NPI|||||||||ST. CLOUD HOSPITAL^L^^^^CMS^NPI^^^1043269798~ST. CLOUD HOSPITAL^L^^^^MN Public Health Lab^Submitter ID^^^739
OBR|1|421832901^EPIC^1.2.840.114350.1.13.145.2.7.2.695071^ISO||57717-1^Newborn screen card data panel^LN|||20230506050000||||||||440500007&Blood spot specimen&SCT
OBX|1|NM|8339-4^BIRTH WEIGHT MEASURED^LN|1|1769.859285|g^gram^UCUM|||||O|||20230506050000-0500|||||||||||||||QST|AOE
OBX|2|NM|57714-8^OBSTETRIC ESTIMATION OF GESTATIONAL AGE^LN|1|32|wk^week^UCUM|||||O|||20230506050000-0500|||||||||||||||QST|AOE
OBX|3|CWE|57713-0^INFANT FACTORS THAT AFFECT NEWBORN SCREENING INTERPRETATION^LN|1|LA12419-0^INFANT IN NICU AT TIME OF SPECIMEN COLLECTION^LN||||||O|||20230506050000-0500|||||||||||||||QST|AOE
OBX|4|CWE|MNDSIB^DOES THE BABY HAVE A DECEASED SIBLING?^99MDH|1|N^No^99MDH||||||O|||20230506050000-0500|||||||||||||||QST|AOE
OBX|5|CWE|MNDEFECT^DOES THE BABY HAVE BIRTH DEFECTS?^99MDH|1|N^No^99MDH||||||O|||20230506050000-0500|||||||||||||||QST|AOE
OBX|6|CWE|MNFAM^FAMILY HISTORY OF DISORDER ON MN SCREENING PANEL^99MDH|1|N^No^99MDH||||||O|||20230506050000-0500|||||||||||||||QST|AOE
OBX|7|CWE|67704-7^FEEDING TYPES^LN|1|LA12418-2^TPN^LN||||||O|||20230506050000-0500|||||||||||||||QST|AOE
OBX|8|CWE|67704-7^FEEDING TYPES^LN|2|LA16914-6^BREAST MILK^LN||||||O|||20230506050000-0500|||||||||||||||QST|AOE
OBX|9|CWE|57723-9^UNIQUE BAR CODE NUMBER OF CURRENT SAMPLE^LN|1|0516199364||||||O|||20230506050000-0500|||||||||||||||QST|AOE
OBX|10|ST|62328-0^DISCHARGE PROVIDER PRACTICE PHONE NUMBER^LN|1|Daniel Davis/218-555-1000||||||O|||20230506050000-0500|||||||||||||||QST|AOE
OBX|11|ST|62324-9^POST-DISCHARGE PROVIDER NAME^LN|1|DAVIS, DANIEL, MD||||||O|||20230506050000-0500|||||||||||||||QST|AOE
OBX|12|ST|62326-4^POST-DISCHARGE PROVIDER PRACTICE NAME^LN|1|Lakeridge Health Revere||||||O|||20230506050000-0500|||||||||||||||QST|AOE`

## Completion Criteria

- [ ] What is the criteria for calling this task complete?

## Tasks

- [ ] What tasks need to be done to fulfill the completion criteria?

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by basiliskus** [comment]
Error is RS we think is causing this issue:
```
2024-01-31 08:42:24 [2024-01-31T16:42:24.735Z] Executed 'Functions.translate-fhir' (Failed, Id=cc75b6b1-8f8f-489f-aae9-96a625325948, Duration=1936ms)
2024-01-31 08:42:24 [2024-01-31T16:42:24.735Z] System.Private.CoreLib: Exception while executing function: Functions.translate-fhir. System.Private.CoreLib: Result: Failure
2024-01-31 08:42:24 [2024-01-31T16:42:24.735Z] Exception: RequiredElementException: Required element order-observation-result conditional was false or value was empty.
2024-01-31 08:42:24 [2024-01-31T16:42:24.735Z] Stack: java.lang.reflect.InvocationTargetException
2024-01-31 08:42:24 [2024-01-31T16:42:24.735Z]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:22)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at com.microsoft.azure.functions.worker.chain.FunctionExecutionMiddleware.invoke(FunctionExecutionMiddleware.java:19)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:125)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:34)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:94)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z]  at java.base/java.lang.Thread.run(Thread.java:833)
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z] Caused by: gov.cdc.prime.router.fhirengine.translation.hl7.schema.ConfigSchemaElementProcessingException: Error encountered while applying: order-observation-result in TILabOrder to FHIR bundle. 
2024-01-31 08:42:24 [2024-01-31T16:42:24.736Z] Error was: Required element order-observation-result conditional was false or value was empty.
```

**Comment by basiliskus** [comment]
The `Observation` resource is not being mapped, which is required, when translating the ORM to FHIR in RS

**Comment by basiliskus** [comment]
According to Ott, it's happening because RS doesn't accept `CWE` for `OBX.3` in HL7 2.5.1. It's still happening for us even if we replace `CWE` for `CE` for MN ORM example message

**Comment by basiliskus** [comment]
Someone in the RS platform team found the bug and has a fix. PR will be available soon

**Comment by basiliskus** [comment]
PR with the fix: https://github.com/CDCgov/prime-reportstream/pull/13224

**Comment by jorg3lopez** [comment]
The observation yaml file had `required: true` under the OBX-2 CE/CWE field, which filtered the values out. By removing this line, the bug was fixed. We are still waiting for the PR to get merge, and then we will wait for it to deploy on Tuesday or Thursday.

**Comment by basiliskus** [comment]
Set story to `blocked` while waiting for https://github.com/CDCgov/prime-reportstream/pull/13224 to be approved and merged
