### ISSUE TITLE
RS Orders and Results Broken

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#942]
# Bug

## Describe the Bug

When trying to submit TI Example ORM/ORU we get the error below.
```
Executed 'Functions.translate-fhir' (Failed, Id=3c6329dc-06cc-4e0b-b0f1-5833aa7aa0a7, Duration=17ms)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z] System.Private.CoreLib: Exception while executing function: Functions.translate-fhir. System.Private.CoreLib: Result: Failure
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z] Exception: SchemaException: Unexpected scheme: null
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z] Stack: java.lang.reflect.InvocationTargetException
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at jdk.internal.reflect.GeneratedMethodAccessor247.invoke(Unknown Source)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:22)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at com.microsoft.azure.functions.worker.chain.FunctionExecutionMiddleware.invoke(FunctionExecutionMiddleware.java:19)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:125)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:34)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:94)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at java.base/java.lang.Thread.run(Thread.java:833)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z] Caused by: org.jooq.exception.DataAccessException: Rollback caused
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:573)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at org.jooq.impl.Tools$3$1.block(Tools.java:6068)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at org.jooq.impl.Tools$3.get(Tools.java:6065)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:579)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:503)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.azure.DatabaseAccess.transactReturning(DatabaseAccess.kt:107)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.runFhirEngine(FHIRFunctions.kt:158)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.doTranslate(FHIRFunctions.kt:131)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.doTranslate$default(FHIRFunctions.kt:125)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.translate(FHIRFunctions.kt:116)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  ... 17 more
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z] Caused by: gov.cdc.prime.router.fhirengine.translation.hl7.SchemaException: Unexpected scheme: null
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.translation.hl7.schema.ConfigSchemaReader.readSchemaTreeUri$prime_router(ConfigSchemaReader.kt:159)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.translation.hl7.schema.ConfigSchemaReader.readSchemaTreeUri$prime_router$default(ConfigSchemaReader.kt:128)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.translation.hl7.schema.ConfigSchemaReader.fromUri(ConfigSchemaReader.kt:69)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.translation.hl7.schema.ConfigSchemaReader.fromFile(ConfigSchemaReader.kt:40)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.translation.hl7.schema.fhirTransform.FhirTransformSchemaReaderKt.fhirTransformSchemaFromFile(FhirTransformSchemaReader.kt:15)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.translation.hl7.FhirTransformer.<init>(FhirTransformer.kt:31)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.translation.hl7.FhirTransformer.<init>(FhirTransformer.kt:27)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.engine.FHIRTranslator.getByteArrayFromBundle$prime_router(FHIRTranslator.kt:190)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.engine.FHIRTranslator.sendTranslated$prime_router(FHIRTranslator.kt:147)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.engine.FHIRTranslator.doWork(FHIRTranslator.kt:83)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.engine.FHIREngine.run(FHIREngine.kt:201)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions$runFhirEngine$newMessages$1.invoke(FHIRFunctions.kt:159)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions$runFhirEngine$newMessages$1.invoke(FHIRFunctions.kt:158)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at gov.cdc.prime.router.azure.DatabaseAccess.transactReturning$lambda$1(DatabaseAccess.kt:107)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:531)
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z]  ... 28 more
2024-03-12 10:16:29 [2024-03-12T15:16:29.519Z] .
```

## Impact

Unable to submit TI example ORM and ORU in local master RS. (possibly staging as well)

## To Reproduce

1. Run the latest master branch code for RS with docker.
2. Submit an example ORM or ORU under the TI repository.
3. See error in RS logs.

## Expected Behavior

When submitting an ORU/ORM, the TI service receives translated FHIR.

## Logs

If applicable, please attach logs to help describe your problem.

## Version

The version or git commit sha of the application that the bug found on.

**Comment by basiliskus** [comment]
The path reference for the schemaName in org setting files in RS has changed in: https://github.com/CDCgov/prime-reportstream/pull/13530 . 

I think they updated our settings in staging, as it seems to be working there, but we need to update our org file for local testing. This means we need to update all `schemaName` values in `prime-router/settings/staging/0166-flexion-staging-results-handling.yml` to start with  `classpath:/` and end with `.yml`

**Comment by basiliskus** [comment]
Added this PR in RS to fix it: https://github.com/CDCgov/prime-reportstream/pull/13674
